apiVersion: v1
kind: Service
metadata:
  name: complete-prodcution-e2e-service
spec:
  selector:
    app: complete-prodcution-e2e-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort